#! /usr/bin/env bash

set -euo pipefail

LINUX_GUIDE=~/code/linux-guide
CORE_FILE=$LINUX_GUIDE/core

echo "pacman" > $CORE_FILE
echo "###########" >> $CORE_FILE
pacman -Qe >> $CORE_FILE
echo "" >> $CORE_FILE
echo "" >> $CORE_FILE
pacman -Qe | wc -l >> $CORE_FILE
echo "" >> $CORE_FILE
echo "" >> $CORE_FILE
echo "nix" >> $CORE_FILE
echo "###########" >> $CORE_FILE
nix-env --query >> $CORE_FILE
cat $CORE_FILE
cd $LINUX_GUIDE
git status
git diff core
