#! /usr/bin/env bash

set -euo pipefail

CORE_FILE=~/code/linux-guide/core

echo "pacman" > $CORE_FILE
echo "###########" >> $CORE_FILE
pacman -Qe >> $CORE_FILE
echo "" >> $CORE_FILE
echo "" >> $CORE_FILE
pacman -Qe | wc -l >> $CORE_FILE
echo "" >> $CORE_FILE
echo "" >> $CORE_FILE
echo "nix" >> $CORE_FILE
echo "###########" >> $CORE_FILE
nix-env --query >> $CORE_FILE
